using Fade.MonoGame.Core;   // Game1
using FadeBasic.Launch;     // GeneratedFade (emitted by FadeBasic.Build)

// MonoGame entry point. The console-style launcher (Launcher.Run<...>) doesn't
// apply here — a MonoGame game boots a Game1 window instead. `GeneratedFade` is
// generated by FadeBasic.Build from the <FadeSource>/<FadeCommand> items in the
// .csproj, and carries the compiled program + its command surface.
//
// (A later iteration may have the Game package generate this file so the
// template ships no Program.cs — see the spec. For now it's explicit.)
public static class Program
{
    public static void Main()
    {
        var fade = new GeneratedFade();
        using var game = new Game1(fade);
        game.Run();
    }
}
