using System.IO;
using System.Linq;
using Fade.MonoGame.Core;   // Game1, GameReloader
using FadeBasic.Launch;     // GeneratedFade (emitted by FadeBasic.Build)

// MonoGame entry point. `GeneratedFade` is generated by FadeBasic.Build from the
// <FadeSource>/<FadeCommand> items in the .csproj and carries the program
// compiled AT BUILD TIME — that's what Release and Web builds run.
//
// In Debug desktop we instead compile your .fbasic from source AT RUNTIME and
// watch it, so editing your Fade code shows the reload border and pressing F1
// hot-swaps the running program (the same flow as the engine's sample game).
// WatchFiles also watches your .png/.fx assets, so content hot-reload still
// works. This dev path is compiled out of Release/Web (FADE_CONTENT_HOTRELOAD is
// Debug-desktop only).
public static class Program
{
    public static void Main()
    {
#if FADE_CONTENT_HOTRELOAD
        // GetRoot() reads the [AssemblyMetadata("ProjectDir")] the .csproj stamps
        // in Debug desktop; find our .csproj under it so the runtime compiler can
        // read <FadeSource> and rebuild on change. (We use GetRoot rather than
        // GameReloader.GetCsprojPath here — the latter's body is #if DEBUG-gated
        // and compiles to a no-op in the Release-built engine package.)
        var projectDir = GameReloader.GetRoot();
        var csprojPath = string.IsNullOrEmpty(projectDir) || !Directory.Exists(projectDir)
            ? null
            : Directory.GetFiles(projectDir, "*.csproj").FirstOrDefault();
        if (!string.IsNullOrEmpty(csprojPath))
        {
            // Mirror the <FadeCommand> items in the .csproj so the runtime compile
            // exposes the same command surface as the build-time generator. (Both
            // types ride in transitively via FadeBasic.MonoGame.Lib.)
            var commands = new FadeBasic.CommandCollection(
                new FadeBasic.Lib.Standard.StandardCommands(),
                new Fade.MonoGame.Lib.FadeMonoGameCommands());

            // Compiles game.fbasic now (populates LatestBuild) and watches
            // .fbasic + assets; F1 in-game swaps to the latest compiled build.
            GameReloader.WatchFiles(csprojPath, commands);

            using var devGame = new Game1(GameReloader.LatestBuild ?? new GeneratedFade());
            devGame.Services.AddService(typeof(Fade.MonoGame.Content.IContentBuilder),
                new Fade.MonoGame.Content.FadeContentBuilder());
            devGame.Run();
            return;
        }
#endif
        // Release / Web / no project on disk: run the build-time compiled program.
        var fade = new GeneratedFade();
        using var game = new Game1(fade);
        game.Run();
    }
}
